repos:
  - repo: local
    hooks:
      - id: ruff check
        name: Linting (ruff)
        language: system
        entry: poetry run ruff check --fix
        types: [python]

      - id: ruff format
        name: Formatting (ruff)
        language: system
        entry: poetry run ruff format
        types: [python]

      - id: ty
        name: Type checking (ty)
        language: system
        entry: poetry run ty check
        types: [python]
        pass_filenames: false

      - id: pytest
        name: Unit Tests (pytest)
        language: system
        entry: poetry run pytest test/unit/
        types: [python]
        pass_filenames: false
