from bliplib.transpiler.interface import Transpiler
from bliplib.errors import TranspilerError


class PythonTranspiler(Transpiler):
    def transpile_function(self, blip_ir: dict) -> str:
        try:
            blip_statements = blip_ir["statements"]

            if len(blip_statements) == 0:
                raise TranspilerError("Cannot generate Python code for an empty Blip program")

            python_statements: list[str] = []

            python_statements.append("""def blip_autogenerated_function(args) -> list[str]:""")

            for stmt in blip_statements:
                match stmt:
                    case {"type": "return"}:
                        string = stmt["expression"]["value"]["value"]
                        python_statements.append(f"""    return ["{string}"]""")

            return "\n".join(python_statements)

        except Exception as err:
            raise TranspilerError() from err

    def transpile_program(self, blip_ir: dict) -> str:
        raise NotImplementedError("Python program transpiling")
