from bliplib.transpiler.interface import Transpiler
from bliplib.errors import TranspilerError


class PythonFunction:
    def __init__(self, statements: list[str]):
        self.__statements = statements

    def serialise(self) -> str:
        signature = """def blip_autogenerated_function(args) -> list[str]:"""

        serial = [signature]

        for stmt in self.__statements:
            serial.append(f"    {stmt}")

        return "\n".join(serial)


class PythonTranspiler(Transpiler):
    def transpile_function(self, blip_ir: dict) -> str:
        try:
            blip_statements = blip_ir["statements"]

            if len(blip_statements) == 0:
                raise TranspilerError("Cannot generate Python code for an empty Blip program")

            function = PythonFunction([f"""return ["{stmt["expression"]["value"]["value"]}"]""" for stmt in blip_statements])

            return function.serialise()

        except Exception as err:
            raise TranspilerError() from err

    def transpile_program(self, blip_ir: dict) -> str:
        raise NotImplementedError("Python program transpiling")
