from bliplib.transpiler.interface import Transpiler
from bliplib.errors import TranspilerError


class PythonTranspiler(Transpiler):
    def transpile_function(self, blip_ir: dict) -> str:
        if len(blip_ir["statements"]) == 0:
            raise TranspilerError("Cannot generate Python code for an empty Blip program")

        return "\n".join(
            [
                """def blip_autogenerated_function(args) -> list[str]:""",
                """    return ["Hello World!"]""",
            ]
        )

    def transpile_program(self, blip_ir: dict) -> str:
        raise NotImplementedError("Python program transpiling")
