from bliplib.transpiler.python import PythonTranspiler


def test_hello_world_function():
    blip_ir = {
        "type": "program",
        "statements": [
            {
                "type": "return",
                "expression": {"type": "expression", "value": {"type": "string_literal", "value": "Hello World!"}},
            }
        ],
    }

    expected_python = "\n".join(
        [
            """def blip_autogenerated_function(input_strs: list[str]) -> list[str]:""",
            """    return ["Hello World!"]""",
        ]
    )

    actual_python = PythonTranspiler().transpile_function(blip_ir)

    assert actual_python == expected_python


def test_hello_world_program():
    blip_ir = {
        "type": "program",
        "statements": [
            {
                "type": "return",
                "expression": {"type": "expression", "value": {"type": "string_literal", "value": "Hello World!"}},
            }
        ],
    }

    expected_python = "\n".join(
        [
            """import argparse""",
            """import sys""",
            """import json""",
            """""",
            """""",
            """class AutogeneratedBlipError(RuntimeError):""",
            """    \"\"\"An error originating from Blip-autogenerated code.\"\"\"""",
            """""",
            """""",
            """def blip_autogenerated_function(input_strs: list[str]) -> list[str]:""",
            """    return ["Hello World!"]""",
            """""",
            """""",
            """def main():""",
            """    argument_parser = argparse.ArgumentParser()""",
            """    argument_parser.add_argument("input_strings", nargs="*", help="Input strings")""",
            """""",
            """    args = argument_parser.parse_args()""",
            """""",
            """    try:""",
            """        input_strings: list[str] = args.input_strings""",
            """        output_strings: list[str] = blip_autogenerated_function(input_strings)""",
            """        print(json.dumps(output_strings))""",
            """        sys.exit(0)""",
            """""",
            """    except AutogeneratedBlipError as err:""",
            """        print(f"Error: {err}", file=sys.stderr)""",
            """        sys.exit(1)""",
            """""",
            """    except Exception as err:""",
            """        print(f"Unknown error encountered while interpreting program: {err}", file=sys.stderr)""",
            """        sys.exit(2)""",
            """""",
            """""",
            """if __name__ == "__main__":""",
            """    main()""",
            """""",
        ]
    )

    actual_python = PythonTranspiler().transpile_program(blip_ir)

    assert actual_python == expected_python


def test_empty_program_raises_an_exception():
    blip_ir = {
        "type": "program",
        "statements": [],
    }

    expected_python = "\n".join(
        [
            """def blip_autogenerated_function(input_strs: list[str]) -> list[str]:""",
            """    raise RuntimeError("Autogenerated Blip code halted without returning a value")""",
        ]
    )

    actual_python = PythonTranspiler().transpile_function(blip_ir)

    assert actual_python == expected_python


def test_hello_world_list_function():
    blip_ir = {
        "type": "program",
        "statements": [
            {
                "type": "return",
                "expression": {
                    "type": "expression",
                    "value": {
                        "type": "list",
                        "elements": [
                            {"type": "expression", "value": {"type": "string_literal", "value": "Hello"}},
                            {"type": "expression", "value": {"type": "string_literal", "value": "World"}},
                        ],
                    },
                },
            }
        ],
    }

    expected_python = "\n".join(
        [
            """def blip_autogenerated_function(input_strs: list[str]) -> list[str]:""",
            """    return ["Hello", "World"]""",
        ]
    )

    actual_python = PythonTranspiler().transpile_function(blip_ir)

    assert actual_python == expected_python
