"""
Unit tests for the Python transpiler.

The transpiler is handed an analysed `Program`, so these compile from Blip source rather than hand-building IR: that exercises
the path the CLI actually takes, and means a test cannot accidentally assert on a tree the analyser would have rejected.
"""

import ast
import textwrap

import pytest

from bliplib.analysis import analyse
from bliplib.errors import TranspilerError
from bliplib.ir import Program, Return, StringLiteral
from bliplib.ir.types import Scalar
from bliplib.parser import Parser
from bliplib.transpiler.python import PythonTranspiler


def compile_program(blip_code: str) -> Program:
    return analyse(Parser().parse(blip_code))


def transpile_function(blip_code: str) -> str:
    return PythonTranspiler().transpile_function(compile_program(blip_code))


def transpile_program(blip_code: str) -> str:
    return PythonTranspiler().transpile_program(compile_program(blip_code))


def __normalise(python_code: str) -> str:
    """Reduce Python source code to a canonical form by round-tripping it through the `ast` module.

    The transpiler emits code with `ast.unparse`, whose exact formatting (quote style, blank lines)
    is not guaranteed to be stable across CPython versions. Comparing normalised code instead of raw
    strings means these tests assert that the right *program* was generated, not how it was laid out.
    """

    return ast.unparse(ast.parse(textwrap.dedent(python_code)))


def assert_same_python(actual: str, expected: str):
    assert __normalise(actual) == __normalise(expected)


def test_hello_world_function():
    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            return ["Hello World!"]
    """

    assert_same_python(transpile_function('ret "Hello World!"'), expected_python)


def test_hello_world_program():
    expected_python = """
        import argparse
        import sys
        import json


        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            return ["Hello World!"]


        def main():
            argument_parser = argparse.ArgumentParser()
            argument_parser.add_argument("input_strings", nargs="*", help="Input strings")

            args = argument_parser.parse_args()

            try:
                input_strings: list[str] = args.input_strings
                output_strings: list[str] = blip_autogenerated_function(input_strings)
                print(json.dumps(output_strings))
                sys.exit(0)

            except Exception as err:
                print(f"Error: {err}", file=sys.stderr)
                sys.exit(1)


        if __name__ == "__main__":
            main()
    """

    assert_same_python(transpile_program('ret "Hello World!"'), expected_python)


def test_empty_program_raises_an_exception():
    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            raise RuntimeError("Autogenerated Blip code halted without returning a value")
    """

    assert_same_python(transpile_function(""), expected_python)


def test_a_program_that_runs_off_the_end_raises_an_exception():
    """Falling off the end of a Blip program is an execution-time error, so the generated function has to raise too."""

    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            x = "unused"
            raise RuntimeError("Autogenerated Blip code halted without returning a value")
    """

    assert_same_python(transpile_function('x = "unused"'), expected_python)


def test_returning_a_list_does_not_wrap_it():
    """The generated function returns a list of strings either way, so only a single string needs wrapping."""

    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            return ["Hello", "World"]
    """

    assert_same_python(transpile_function('ret ["Hello", "World"]'), expected_python)


def test_identity_function():
    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            return _blip_input
    """

    assert_same_python(transpile_function("ret input"), expected_python)


def test_input_is_renamed_so_a_blip_variable_cannot_collide_with_it():
    """
    `input` is renamed because it would shadow the Python builtin.

    The name it is renamed to starts with an underscore, which no Blip identifier can, so a Blip program cannot declare a
    variable that silently overwrites the parameter.
    """

    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            input_strs = "not the parameter"
            return [input_strs]
    """

    assert_same_python(transpile_function('input_strs = "not the parameter"\nret input_strs'), expected_python)


def test_variables_and_literals():
    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            number = 987
            flag = True
            colour = "blue"
            colours = [colour, "black"]
            return colours
    """

    blip_code = 'number = 987\nflag = true\ncolour = "blue"\ncolours = [colour, "black"]\nret colours'

    assert_same_python(transpile_function(blip_code), expected_python)


def test_concatenation_becomes_addition():
    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            abc = "A" + "B" + "C"
            return [abc + "123" + abc]
    """

    assert_same_python(transpile_function('abc = "A" "B" "C"\nret abc "123" abc'), expected_python)


def test_indexing_becomes_a_subscript():
    expected_python = """
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            return [_blip_input[0]]
    """

    assert_same_python(transpile_function("ret input[0]"), expected_python)


def test_decomposition_becomes_a_full_match():
    expected_python = r"""
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            import re
            email = _blip_input[0]
            _blip_match = re.fullmatch("(?P<username>.*?)@.*?", email, flags=re.DOTALL)
            if _blip_match is None:
                raise RuntimeError("Decomposition failed: 'email' does not match the pattern 'username \"@\" *'")
            username = _blip_match.group("username")
            return [username]
    """

    assert_same_python(transpile_function('email = input[0]\nemail -> username "@" *\nret username'), expected_python)


def test_a_trailing_name_in_a_decomposition_takes_the_remainder():
    expected_python = r"""
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            import re
            name = _blip_input[0]
            _blip_match = re.fullmatch("(?P<first>.*?)\\.(?P<last>.*?)", name, flags=re.DOTALL)
            if _blip_match is None:
                raise RuntimeError("Decomposition failed: 'name' does not match the pattern 'first \".\" last'")
            first = _blip_match.group("first")
            last = _blip_match.group("last")
            return [first + " " + last]
    """

    blip_code = 'name = input[0]\nname -> first "." last\nret first " " last'

    assert_same_python(transpile_function(blip_code), expected_python)


def test_a_leading_literal_in_a_decomposition_must_be_a_prefix():
    """A literal is part of the match rather than something merely found, so a leading one anchors the start of the string."""

    expected_python = r"""
        def blip_autogenerated_function(_blip_input: list[str]) -> list[str]:
            import re
            xml = _blip_input[0]
            _blip_match = re.fullmatch("<foo>(?P<content>.*?)</foo>", xml, flags=re.DOTALL)
            if _blip_match is None:
                raise RuntimeError("Decomposition failed: 'xml' does not match the pattern '\"<foo>\" content \"</foo>\"'")
            content = _blip_match.group("content")
            return [content]
    """

    blip_code = 'xml = input[0]\nxml -> "<foo>" content "</foo>"\nret content'

    assert_same_python(transpile_function(blip_code), expected_python)


def test_re_is_only_imported_by_a_program_that_decomposes():
    """
    The import sits inside the function because `transpile_function` emits the function on its own.

    A caller drops that function into a module of their own, so a function needing something imported alongside it could not be
    dropped anywhere. A program with no decomposition needs nothing, and gets nothing.
    """

    assert "import re" not in transpile_function('ret "Hello World!"')
    assert "import re" in transpile_function('x = input[0]\nx -> * "@" *\nret x')


def test_an_unanalysed_program_is_refused_rather_than_guessed_at():
    unanalysed = Parser().parse('ret "Hello World!"')
    returned = unanalysed.statements[0]
    assert isinstance(returned, Return)
    assert returned.expression.blip_type is None

    with pytest.raises(TranspilerError):
        PythonTranspiler().transpile_function(unanalysed)


@pytest.mark.parametrize(
    "awkward",
    [
        pytest.param('double " quote', id="double quote"),
        pytest.param("single ' quote", id="single quote"),
        pytest.param("backslash \\ and \\n escape", id="backslash and newline"),
        pytest.param("both \" and ' quotes", id="both double and single quotes"),
        pytest.param("newline \n in the middle", id="newline in the middle"),
        pytest.param("tab \t and carriage return \r", id="tab and carriage return"),
        pytest.param('triple """ quotes', id="triple quotes"),
        pytest.param("unicode é中\U0001f600", id="unicode"),
    ],
)
def test_awkward_string_literals_are_handled_properly(awkward: str):
    program = Program(statements=[Return(expression=StringLiteral(value=awkward, blip_type=Scalar.STRING))])
    actual_python = PythonTranspiler().transpile_function(program)

    # The generated function must parse, and calling it must give back the original string
    namespace: dict = {}
    exec(actual_python, namespace)  # noqa: S102
    assert namespace["blip_autogenerated_function"]([]) == [awkward], f"String was mangled: {awkward!r}"


def test_transpiled_program_is_valid_python():
    """Whatever the transpiler emits must at least be syntactically valid Python."""

    program = Program(statements=[Return(expression=StringLiteral(value='awkward " string', blip_type=Scalar.STRING))])

    ast.parse(PythonTranspiler().transpile_program(program))
