import pytest
from bliplib.transpiler.python import PythonTranspiler
from bliplib.errors import BlipError


def test_hello_world_function():
    blip_ir = {
        "type": "program",
        "statements": [
            {
                "type": "return",
                "expression": {"type": "expression", "value": {"type": "string_literal", "value": "Hello World!"}},
            }
        ],
    }

    expected_python = "\n".join(
        [
            """def blip_autogenerated_function(args) -> list[str]:""",
            """    return ["Hello World!"]""",
        ]
    )

    actual_python = PythonTranspiler().transpile_function(blip_ir)

    assert actual_python == expected_python


def test_empty_program_fails_to_transpile():
    blip_ir = {
        "type": "program",
        "statements": [],
    }

    with pytest.raises(BlipError):
        PythonTranspiler().transpile_function(blip_ir)
