from bliplib.transpiler.python import PythonTranspiler


def test_hello_world_function():
    blip_ir = {
        "type": "program",
        "statements": [
            {"type": "return", "expression": {"type": "expression", "value": {"type": "string_literal", "value": "Hello World!"}}}
        ],
    }

    expected_python = "\n".join(
        [
            """def blip_autogenerated_function() -> list[str]:""",
            """    return ["Hello World!\"]""",
        ]
    )

    actual_python = PythonTranspiler().transpile_function(blip_ir)

    assert actual_python == expected_python
